# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUZFJ0SJggHj_JdQseINFnK-WBWnE53J
"""

import requests

# API Key and URL
API_KEY = "0d1f033bfe4e9ce40ec66d1687daf6fc"
BASE_URL = "http://api.openweathermap.org/data/2.5/weather?"

# Function to fetch and display weather
def get_weather(city):
    if not city:
        return "Please enter a city name"

    # Construct the URL with the city name and API key
    url = BASE_URL + "q=" + city + "&appid=" + API_KEY + "&units=metric"

    try:
        # Send a GET request to the API
        response = requests.get(url)
        data = response.json()

        if data["cod"] == "404":
            return "City not found!"
        else:
            main = data["main"]
            weather = data["weather"][0]
            temperature = main["temp"]
            pressure = main["pressure"]
            humidity = main["humidity"]
            weather_description = weather["description"]

            # Return weather info as text
            return (f"Temperature: {temperature}°C\n"
                    f"Pressure: {pressure} hPa\n"
                    f"Humidity: {humidity}%\n"
                    f"Description: {weather_description.capitalize()}")
    except Exception as e:
        return "Error fetching data"

# Input city name and fetch weather
city = input("Enter city name: ")
print(get_weather(city))

